howtowhale/dvm

- dvm.sh
> Actually make the binary executable.

- dvm.sh
This finishes up more of `dvm install X.Y.Z`.
In the process, I implemented `dvm ls-remote` as well.
It also needs
> Round out install.

- README.md
- bash_completion
- dvm.sh
This adds bash completion, straight from `nvm` but with some trimming. I've also fleshed out the README. We still have documented features that aren't implemented, so we'll need to trim those out later.
> bash (and zsh) completion

- .travis.yml
- dvm.sh
> Implement dvm ls.

- .gitignore
- dvm.sh
Alias management, including `default`.
> Alias and unalias

- dvm.sh
Fun fact: I'm pretty sure that `nvm uninstall ../../../..` (or some variant thereof) will wipe out your home directory.
> Implement uninstall, very carefully.

- README.md
Added an illustrative PNG as well as the error that should lead people here.
> Little terminal section

- dvm.sh
These were TODOs before `dvm use` was implemented.
> `dvm use` after a successful `dvm install`

- dvm.sh
Support experimental Docker binaries. Closes #26.
> Experimental versions

- dvm-helper.go
Originally I was just coming to fix `PATH`s that have spaces and ended up running `go fmt` and `go vet` on this as well.
> go fmt, go vet, and a fix for PATH with space

- dvm-helper.go
> Automatically dvm use after dvm install

- install.sh
* Install `dvm` during install.sh run
* For install, rely on `dvm_download` to get both `dvm.sh` and `dvm-helper`.
> Use dvm_download in install.sh

- checksum/checksum.go
- dvm-helper.go
> Verify Docker client checksum

- README.md
This makes a minor note about upgrading from the old version that was very shell and git driven.
There were a few other things I had to do on my machine, since my `DVM_DIR` was not the default but my own source layout. I make no such assumptions here.
Ping @carolynvs and @smashwilson for review.
> Make note about upgrading from previous release.

- dvm.sh
In support of #61.
/cc @filler
> Make dvm.sh POSIX compatible again

- Makefile
* Upload scripts to cloud files automatically during release.
* Update download urls to use the exact version for the release instead of latest.
> Prep install scripts for release

- bash_completion
Adds in upgrade to the list of bash completions. Once we switch to kingpin this can be automated while keeping our fancy completions for versions, aliases, etc.
> upgrade is one of the commands, expose it!

- Makefile
> Bring on that Linux 32 bit support

- Makefile
> Include bash_completion in the bundle for deploy

- dvm.sh
Restore the DVM_OUTPUT variable to avoid running source ""
> Fix missing DVM_OUTPUT

- README.md
> Workaround W10 oddities when installing

- dvm-helper/dvm-helper.windows.go
- dvm.ps1
- install.ps1
> Handle whitespace in Windows paths

- README.md
- install.ps1
> Limit PowerShell to v4 or higher

- Makefile
Fixes https://github.com/getcarina/carina/issues/111
> Build Windows 32-bit

- dvm-helper/dvm-helper.go
This method was not checking if the response object was initialized.
> Add nil check before dereferencing response object

- dvm-helper/dvm-helper.go
It's no longer feasible to check if a version exists before installing because we can no longer determine the correct location based on the version number, and Docker no longer tags all of
its releases. So the only way to check if a version exists is to check multiple locations for the existence of a file, so may as well just do the install at that point.
Related to #170 .
> Never check a version before installing

- install.ps1
Just a very minor fix on TLS/SSL version mismatch which cause the download fail
> Fix the DownloadFile failing problem on TLS/SSL
