dvm.sh

This'll include support for aliases and system docker, but not `.dvmrc` files.
Fixes #3.

Implement dvm use

---

dvm.sh

This fixes a bug in `dvm ls` that was causing it to omit certain versions.
Docker's versions are easier to sort than Node's, it turns out.

Fix `dvm ls`.

---

dvm-helper.386.go
dvm-helper.amd64.go
dvm-helper.darwin.go
dvm-helper.go
dvm-helper.linux.go
dvm-helper.nix.go
dvm-helper.windows.go
path/path.go
path/path.nix.go
path/path.windows.go

I've hunted down all usage of the `runtime` package and moved that logic into separate files based on the OS and ARCH.
In addition, I moved the path environment variable manipulation into a subpackage so that things are a bit more tidy.
Fixes #39

Break platform specific functionality of dvm-helper up

---

build
dvm.ps1
dvm.sh
install.sh

Generate *.sha256 files for each binary during the build.
I've also updated the build script so that we can either build for the current platform (default), or build everything with `./build all`.
Fixes #34

Verify checksum of dvm-helper

---

dvm.cmd
dvm.ps1
dvm.sh
install.ps1
install.sh

* Updated all install and wrapper scripts to move downloading dvm-help to install. If dvm-helper is missing when the user runs `dvm`, a message is printed that they need to reinstall.
* Fixed `install.sh` so that the latest version of dvm-helper is always installed.
* Tweaked post-install output based on user feedback.

Download dvm helper during install

---

Dockerfile.build
Makefile
README.md
install.ps1
install.sh
release.sh

**Build and Test Process**
Use `make` to build and output to `dvm-helper/dvm-helper`. Use `make cross-build` to build all platforms (then manually copy the desired binary from the repo-path/bin).
**Release Process**
1. `git checkout master`
2. `git pull`
3. `git tag 0.2.0 -a -m ""`.
4. `git push --follow-tags`
5. `./release.sh 0.2.0`

Streamline release process

---

README.md
bash_completion
install.sh

Bring back that bash and zsh completion.
This uses a custom written `__dvm_ls` instead of using `dvm-helper ls` because we need the output clean. Otherwise we end up with this fun output:
```bash
$ dvm use[TAB]
(1.10.0-dev,  ->            1.8.2         carina        experimental
(1.9.0)       0cdc96c)      build         default       system
```
At any rate, we're back!
```bash
$ dvm [TAB]
alias        install      ls           uninstall    which
current      list         ls-alias     unload
deactivate   list-alias   ls-remote    use
help         list-remote  unalias      version
$ dvm u[TAB]
unalias    uninstall  unload     use
$ dvm us[TAB]
$ dvm use [TAB]
1.8.2         1.9.0         carina        default       experimental
```

Bash completion

---

dvm-helper/dvm-helper.go

It doesn't match dvm's release structure 1:1 (version at end).

Fix up the Docker URL.

---

dvm.sh

This keeps up our zsh compatibility the rest of the way.

Bring back dvm_has in order to set DVM_CD_FLAGS

---

Makefile

A recent patch (14d3ecbbb04aa90fcb34907a275999d28aca20d4) added a target
for Linux 32 bit support, but without adding `linux32` to the
`cross-build`, nothing actually happens.
This patch should close the loop on that.
This is a follow-up to https://github.com/getcarina/dvm/pull/69 and should resolve https://github.com/getcarina/dvm/issues/68.

Add `linux32` to `cross-build` target

---

dvm-helper/dvm-helper.go

dvm list 1.9 should return all versions starting with 1.9.
dvm use 1.9 should check if 1.9 is installed without wildcards
Fixes #77

Make dvm use and dvm list <pattern> play nice

---

dvm-helper/dvm-helper.go

Automatically use the `$GITHUB_TOKEN` environment variable, if present. The user can also explicitly set the token using `--github-token`.
When a request fails due to rate limiting, display the following message:
```
Your GitHub API rate limit has been exceeded. Set the GITHUB_TOKEN environment variable
or use the --github-token parameter with your GitHub personal access token to authenticate
and increase the rate limit.
```
Fixes #78

Use GitHub token if available

---

dvm-helper/dvm-helper.go

I was previously using a hand-rolled check in `dvm ls` for when we should display `system`. Since pattern can be any globbing pattern, I've switched to using globs to check if system matches, and should be displayed.
Fixes #81

Fix regression where system didn't show in ls

---

install.sh

Despite the misleading github syntax highlighting, "\t" is not a valid escape syntax for "echo", so dvm tells you to actually type "\tsource" which is not a command on my system :).

use literal tab

---

dvm.sh

I run `dvm use` in my `.zshrc`. If I open multiple windows at once there seems to be a race condition when deleting this file. This seems to fix it.
Thanks for dvm!

Race condition when removing "$DVM_DIR/.tmp/dvm-output.sh"

---

dvm.sh

1. source dvm.sh, I do this in my bash_profile
2. write a script that uses dvm
3. call the script. Currently, it fails because it can't find the dvm function
The proposed change makes the above scenario work.

Enable scripts to call the dvm function

---

dvm-helper/dockerversion/dockerversion.go
dvm-helper/dvm-helper.go
dvm-helper/dvm-helper.nix.go
dvm-helper/dvm-helper.windows.go

I grabbed this one because using the semver library also helps setup the fix for #95.
I've wrapped up all the logic related to the version into a class `dockerversion.Version`, which manages the version + optional alias.
```
$ dvm ls
->	1.9.1
system (1.10.3)
experimental (1.11.0-dev+6c2f438)
1.11.0
```
Closes #92.

Use semver for sorting

---

dvm-helper/dockerversion/dockerversion.go
dvm-helper/dvm-helper.go
dvm-helper/dvm-helper.nix.go
dvm-helper/dvm-helper.windows.go
dvm-helper/util.go

`dvm install` checks the version being installed and `version >= 1.11.0`, it first downloads the archive, and then extracts the binary from it. Experimental releases are still shipped the same as before, so we can continue to get the experimental docker client by hitting the experimental mirror and downloading `docker-latest`.
Closes #95

Handle archived Docker releases

---

dvm.sh

Ran across these bugs while looking into #101; this `sh` source was a little broken, so I touched it up. (=

Handle spaces in $DVM_DIR path

---

dvm.sh

Using export -f func under zsh will print the function body to console, so use autoload seems better for this case.

fix dvm.sh under zsh

---

dvm-helper/dvm-helper.go

Actions now return errors. The default handling isn't as nice as what we have currently (formatting, coloring, etc) so as a quick fix, I'm just returning nil and keeping our current error handling.
Closes #103

Update cli action signature

---

dvm-helper/dvm-helper.go

Tags appear to be limited to the last X number of valid tags (not sure what X is.) Sadly, I still need to use 1.8.3 for some systems, but it is now past the X cutoff. This allows you to use any release vs using tags

Use releases

---

dvm-helper/dvm-helper.go

Those among us doomed to deal with corporate proxies might be able to download binaries to a local mirror or use something like Artifactory.
Suggestion: "dvm" would accept a MIRROR_URL environment variable that points to another place where the Docker binaries were previously downloaded.

Option to pick a local mirror for Docker binaries

---

dvm-helper/dvm-helper.go
dvm-helper/dvm-helper.nix.go
dvm-helper/dvm-helper.windows.go
dvm.ps1
dvm.sh

Support home-brew installations where the installation directory is `/usr/local/opt/dvm` (containing dvm.sh and the dvm-helper binary) while the dvm home directory is located at `~/.dvm` (containing temp files and docker binaries).
This is some legwork to prepare for distributing dvm via homebrew. See https://github.com/getcarina/dvm/issues/85#issuecomment-225044152 for context as to why we want that.

Do not assume that install dir and home dir are the same

---

Makefile
dvm-helper/dvm-helper.go

Builds for package managers have upgrade disabled, so that in-place upgrades don't screw up their chocolatey/homebrew installation.
This is hopefully the last step to prepare dvm to be distributed via a package manager like homebrew or chocolatey. See #85.

Conditionally disable the upgrade command

---

.gitignore
.travis.yml
Makefile
glide.lock
glide.yaml

* At the moment this assumes that glide is on the path (`brew install glide`). 
* I will circle back and improve the "just clone and run make" experience for all platforms if we settle on this path.
Closes #122

Use glide to manage dependencies

---

dvm-helper/dockerversion/dockerversion.go

When the new release format was added (tgz vs. direct binary downloads), experimental builds were still using the old format. Now all experimental builds are archived and this fixes `docker install experimental` which will now correctly download and install docker 1.12-rc4.
Fixes #127.

Use archived binary releases for experimental builds

---

dvm.sh

in addition to c326389 any commands should be called by `command` or `builtin` to avoid any shell script overloads

"escape" invoked shell commands

---

.travis.yml

Go 1.7 has a fix to work with Mac OS Sierra's backwards incompatible changes.
Fixes the following runtime error when carina decides if we have checked for updates within the last 24 horus:
```
failed MSpanList_Insert 0x755588 0xcbde9d7ef878 0x0
fatal error: MSpanList_Insert
```

Build with go 1.7

---

.travis.yml
Makefile

Workaround problems with deploying from Travis to cloud files, by running with `sudo: required`.
Also
* Speed up build by not running get-deps more than once
* Rename `make dvm-helper` to `make local` to match carina's dev setup.

Fix deploy

---

dvm-helper/dockerversion/dockerversion.go
dvm-helper/dockerversion/dockerversion_test.go
dvm-helper/dvm-helper.go
dvm-helper/dvm-helper_test.go
glide.lock
glide.yaml

Fixes #152.
* Handle Docker's new versioning scheme, which uses the version tag to differentiate between editions, e.g `17.3.0-ce`
* Exclude pre-releases by default. 
Previously, we always excluded versions with prerelease tag. Now that Docker uses the tag for non-prerelease versions, we need to be smarter about what to show when. 
To display prereleases, use the `-pre` flag, e.g. `dvm list-remote -pre 1.13`

Support new release versioning

---

dvm-helper/dvm-helper.go

* Don't call use when use initiated the install.
* Don't validate the Docker version when installing the detected Docker
version.
* Don't validate the Docker version when using what was just installed,
or something we know is already installed.

Remove unnecessary checks that a version exists

---

Makefile
dvm-helper/dockerversion/dockerversion.go
dvm-helper/dockerversion/dockerversion_test.go
dvm-helper/dvm-helper.go
dvm-helper/dvm-helper_test.go

Now that `dvm list-remote --pre` exists, we should allow installing a prerelease.

Support installing prereleases

---

dvm-helper/dockerversion/dockerversion.go
dvm-helper/dockerversion/dockerversion_test.go
dvm-helper/dvm-helper.go

The new Docker version scheme can have leading zeroes in the version parts which isn't strictly compatible with semver. So we must preserve the original string value in order to download and list it
properly.
Fixes #152

Handle leading zeros

---

dvm-helper/dockerversion/dockerversion.go
dvm-helper/dockerversion/dockerversion_test.go
dvm-helper/dvm-helper.go

#160 caused a regression with `dvm use experimental` which is unique in that it stores the docker binary under the alias instead of the version.

Fix regression with use experimental

---

install.ps1

When I moved the install scripts to their new home, I fat-fingered the Windows checksum URL. Fixes #162

Fix URL to windows checksum URL

---

dvm.sh

When we use **command** to execute any **built-in** command, first it'll look inside the **PATH** variable for any command that the argument passed may match, if it finds any command that match, then it'll execute that command, if it doesn't find any command in the **PATH**, then it'll look for **built-in** commands of your **command shell** and then execute it.
OSX has a **cd** command located at `/usr/bin/cd` and in general it's inside the **PATH** variable. But if you use **ZSH** or any other shell, you should be using their **built-in** commands.
For example, for who use **ZSH**, the **built-in** commands may be located at `/usr/local/Cellar/zsh/<zsh_version>/share/zsh/functions`. And in this case the **built-in** **cd** command it's inside this folder, more precisely at …

Use built-in Change Directory(cd) command

---

dvm-helper/dockerversion/dockerversion.go
dvm-helper/dockerversion/dockerversion_test.go
dvm-helper/dockerversion/edge_version.go
dvm-helper/dockerversion/edge_version_test.go
dvm-helper/dockerversion/testdata/edge_releases.html
dvm-helper/dvm-helper.go
dvm-helper/dvm-helper.nix.go
dvm-helper/dvm-helper.windows.go
dvm-helper/dvm-helper_test.go
dvm-helper/internal/test/testdata.go
dvm-helper/util.go

Fixes #169, so that `dvm install edge` works. It lists the contents of `https://download.docker.com/OS/static/edge/ARCH/` and installs the latest version.
I've renamed from experimental to edge because that's what Docker calls these builds now. This is a breaking change but since it hasn't been working for months (because docker stopped releasing to the old static url), it's already broken.

Support "edge" releases

---

dvm-helper/dockerversion/dockerversion.go
dvm-helper/dockerversion/dockerversion_test.go

Fixes #179 by not using checksums for the new download location (e.g. https://download.docker.com/mac/static/stable/x86_64/).

 New releases are no longer published with a checksum 

---

Makefile
dvm-helper/dockerversion/dockerversion.go
dvm-helper/dockerversion/edge_version.go
dvm-helper/dockerversion/query.go
dvm-helper/dvm-helper.go
dvm-helper/dvm-helper.nix.go
dvm-helper/dvm-helper.windows.go
dvm-helper/dvm-helper_test.go

`ls-remote` now hits up the old tags, and checks in the new fileshare locations for all the versions (both prerelease and stable).
Related to #170.

Fix ls-remote

---

dvm-helper/dockerversion/dockerversion.go
dvm-helper/dockerversion/dockerversion_test.go
dvm-helper/dvm-helper.go
dvm-helper/dvm-helper.nix.go
dvm-helper/dvm-helper.windows.go
dvm-helper/dvm-helper_test.go
dvm-helper/internal/downloader/downloader.go
dvm-helper/util.go

Docker publishes releases that don't have a prerelease suffix (e.g. `-rc`) to the test location (look in https://download.docker.com/mac/static/test/x86_64/ and you'll see `17.10.0-ce`). Then some time later, when the version is ready for a final release, they publish a new release with the same version to the stable location.
Since we can't tell where to find a version based on its value anymore, first try downloading from stable, then if that fails, check if there's a test release available.
Related to #170.

Retry failed release downloads from test location 

---

.travis.yml
Makefile

* Use go 1.11 only for faster builds.
We are currently building against go 1.7 - 1.10 but I'm not sure at this point that's terribly helpful? I'd rather just build against the current go version (especially as go fmt/vet and other tools differ in what they enforce across versions).
* Add a homebrew target. I keep forgetting how to publish the latest version of dvm to homebrew. 😊 This has been sitting uncommitted in my local repo for a year?
* Travis has deprecated containerized builds. So I'm removing that config option as it's misleading.

Tweak CI Build

---

dvm-helper/dockerversion/dockerversion.go
dvm-helper/dockerversion/dockerversion_test.go
dvm-helper/dvm-helper.go
dvm-helper/dvm-helper.nix.go
dvm-helper/dvm-helper.windows.go
dvm-helper/internal/config/config.go
dvm-helper/internal/downloader/downloader.go
dvm-helper/util.go

Download docker binary to `~/.dvm/.tmp` instead of `/tmp/dvm-*` so that when we copy it into the dvm home directory afterwards we can always use a rename safely. This avoids this dreaded cross partition move error `invalid cross-device link`.
Fixes #188

Use dvm tmp for docker downloads
